title: Nilam Reshim # your name (or website title) here
logo: "/images/profile_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Nilam 
  <br><br>
  Reshim 
  <br><br>
  <a href="https://in.linkedin.com/in/nilamreshim">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-177229918-1 # your Google Analytics tracking ID here
