title: Nilam Reshim # your name (or website title) here
logo: "/images/profile_logo.jpg?raw=true" # your photo (or logo) here<br><br><br><br>
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <br><br>
  Experienced Multi-facet IT professional like to solve business problems with technology.
  <br><br>
  "Technology is best when it helps you get business"
  <br><br>
  <a href="https://in.linkedin.com/in/nilamreshim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-177412126-1 # your Google Analytics tracking ID here
